// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'container-trashed-now'
  | 'pref-enable'
  | 'pref-help'
  | 'pref-input'
  | 'pref-title'
  | 'timeline-menu-open'
  | 'timeline-spike-heading'
  | 'timeline-spike-note'
  | 'timeline-tab-label'
  | 'timeline-trashed-now'
  | 'timeline-trashed-now-unnamed';
