// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck
export type FluentMessageId =
  | 'container-trashed-now'
  | 'pref-help'
  | 'pref-hide-timeline-notes'
  | 'pref-hide-timeline-notes-help'
  | 'pref-title'
  | 'timeline-approaching-size-limit'
  | 'timeline-menu-open'
  | 'timeline-spike-heading'
  | 'timeline-spike-note'
  | 'timeline-tab-label'
  | 'timeline-trashed-now'
  | 'timeline-trashed-now-unnamed'
  | 'vocabulary-recovered';
